services:
  caffe_pos_1:
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: lukemiller/docker_devenvs:caffe
    ports:
    - 8888:8888
    volumes:
    - /home/lukealexmiller/inception_pos:/root/local
    - nvidia_driver_384.59:/usr/local/nvidia:ro
  caffe_pos_2:
    devices:
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: lukemiller/docker_devenvs:caffe
    ports:
    - 8889:8888
    volumes:
    - /home/lukealexmiller/inception_pos:/root/local
    - nvidia_driver_384.59:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.59:
    external: true
