version: '2'
services:
    digits:
        image: nvidia/digits:latest
        volumes:
            - /home/lukealexmiller/trainer:/root/local
            - /home/lukealexmiller/jobs:/jobs
        ports:
            - "5000:5000"

    main1:
        image: lukemiller/docker_devenvs:caffe
        devices:
            - /dev/nvidia0
        volumes:
            - /home/lukealexmiller/trainer:/root/local
            - /home/lukealexmiller/jobs:/jobs
        ports:
            - "8887:8888"
    main2:
        image: lukemiller/docker_devenvs:caffe
        devices:
            - /dev/nvidia1      
        volumes:
            - /home/lukealexmiller/trainer:/root/local
            - /home/lukealexmiller/jobs:/jobs
        ports:
            - "8889:8888"

