services:
  digits:
    devices:  
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: nvidia/digits:latest
    ports:
    - 5000:5000
    restart: always
    volumes:
    - /home/lukealexmiller/trainer:/root/local
    - nvidia_driver_384.59:/usr/local/nvidia:ro
  main1:
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: lukemiller/docker_devenvs:caffe
    ports:
    - 8888:8888
    volumes:
    - /home/lukealexmiller/trainer:/root/local
    - nvidia_driver_384.59:/usr/local/nvidia:ro
  main2:
    devices:
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: lukemiller/docker_devenvs:caffe
    ports:
    - 8889:8888
    volumes:
    - /home/lukealexmiller/trainer:/root/local
    - nvidia_driver_384.59:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.59:
    external: true
