version: '2'
services:
    preseed:
        image: tensorflow_src:objdet_api
        devices:
            - /dev/nvidia1
        volumes:
            - /home/lukealexmiller/objdet_api/models:/root/models
            - /home/lukealexmiller/objdet_api/data/preseed/input:/root/input
            - /home/lukealexmiller/objdet_api/data/preseed/output:/root/output
            - /home/lukealexmiller/objdet_api/configs/head:/root/config
            - /home/lukealexmiller/objdet_api/scripts:/root/scripts
        working_dir: /root/scripts
        command:
            python /root/scripts/preseed.py
# python -m cProfile -s time -o /root/scripts/log.txt /root/scripts/preseed.py