services:
  export_model:
    command: bash -c "cp /root/scripts/ssd_nas_mobile_feature_extractor* /tensorflow/models/research/object_detection/models
      && cp /root/scripts/model_builder* /tensorflow/models/research/object_detection/builders
      && cp /root/scripts/ssd_mobilenet_v1_feature_extractor.py /tensorflow/models/research/object_detection/models
      && python object_detection/export_inference_graph.py --input_type image_tensor
      --pipeline_config_path /root/model/pipeline.config --trained_checkpoint_prefix
      /root/model/train/model.ckpt-105000 --output_directory /root/model/exported_model-105000"
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow_src:objdet_api
    volumes:
    - /home/lukealexmiller/objdet_api/models/faster_rcnn_inception_resnet_v2_atrous_head_2018_01_03:/root/model
    - /home/lukealexmiller/objdet_api/scripts:/root/scripts
    - nvidia_driver_384.59:/usr/local/nvidia:ro
    working_dir: /tensorflow/models/research/
  prep_data:
    command: bash -c "python ./create_pascal_tf_record.py \ --data_dir=./ --year=VOC2007
      --label_map_path=./head_label_map.pbtxt \ --ignore_difficult_instances=True
      --output_path=./head_train.record --set=train && python ./create_pascal_tf_record.py
      \ --data_dir=./ --year=VOC2007 --label_map_path=./head_label_map.pbtxt \ --ignore_difficult_instances=True
      --output_path=./head_val.record --set=val"
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow_src:objdet_api
    volumes:
    - /home/lukealexmiller/objdet_api/data/raw/heads:/root/data/VOCdevkit
    - nvidia_driver_384.59:/usr/local/nvidia:ro
    working_dir: /root/data/VOCdevkit
  prep_data_mscoco:
    command: bash -c "./create_mscoco_tf_record.sh"
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow_src:objdet_api
    volumes:
    - /home/lukealexmiller/objdet_api/data:/root/data
    - /home/lukealexmiller/objdet_api/scripts:/root/scripts
    - nvidia_driver_384.59:/usr/local/nvidia:ro
    working_dir: /root/scripts
  prep_data_nbs:
    command: jupyter notebook
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow_src:objdet_api
    ports:
    - 8888:8888
    volumes:
    - /home/lukealexmiller/objdet_api/data:/root/data
    - /home/lukealexmiller/objdet_api/nbs:/root/nbs
    - /home/lukealexmiller/frames:/root/frames
    - nvidia_driver_384.59:/usr/local/nvidia:ro
    working_dir: /root/nbs
version: '2'
volumes:
  nvidia_driver_384.59:
    external: true
