services:
  tensorboard:
    command: tensorboard --logdir=/root/model
    devices:
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow_src:objdet_api
    ports:
    - 6006:6006
    volumes:
    - /home/lukealexmiller/objdet_api/models/faster_rcnn_resnet101_carts_heads_02_11_2017:/root/model
    - nvidia_driver_384.59:/usr/local/nvidia:ro
    working_dir: /root/model
  train:
    command: python object_detection/train.py --logtostderr --pipeline_config_path=/root/model/carts_heads.config
      --train_dir=/root/model/train
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow_src:objdet_api
    volumes:
    - /home/lukealexmiller/objdet_api/data/raw/carts_heads:/root/data/VOCdevkit
    - /home/lukealexmiller/objdet_api/models/faster_rcnn_resnet101_carts_heads_02_11_2017:/root/model
    - nvidia_driver_384.59:/usr/local/nvidia:ro
    working_dir: /tensorflow/models/research/
  val:
    command: python object_detection/eval.py --logtostderr --pipeline_config_path=/root/model/carts_heads.config
      --checkpoint_dir=/root/model/train --eval_dir=/root/model/eval
    devices:
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow_src:objdet_api
    volumes:
    - /home/lukealexmiller/objdet_api/data/raw/carts_heads:/root/data/VOCdevkit
    - /home/lukealexmiller/objdet_api/models/faster_rcnn_resnet101_carts_heads_02_11_2017:/root/model
    - nvidia_driver_384.59:/usr/local/nvidia:ro
    working_dir: /tensorflow/models/research/
version: '2'
volumes:
  nvidia_driver_384.59:
    external: true
